import { ChangeDetectionStrategy, Component, DestroyRef, OnInit, inject, signal } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { TranslateModule, TranslateService } from '@ngx-translate/core';
import { AlertCircle, CheckCircle, DownloadCloud, Loader, LucideAngularModule } from 'lucide-angular';
import { VX_FORM_A11Y } from '@virteex/shared/ui-a11y';
import { FORMAT_PIPES } from '@virteex/shared/ui-i18n';
import {
  DataTransferDataset,
  DataTransferFormat,
  DataTransferRun,
  DataTransferService,
  saveFile,
} from '../../core/api/data-transfer.service';
import { NotificationService } from '../../core/services/notification';
import { VxBadgeComponent } from '../../shared/components/badge';
import { ListShellComponent } from '../../shared/components/gestures';
import { transferStatusKey, transferStatusTone } from './transfer-status';
import { VX_SORT, sortable } from '../../shared/components/sort';

/**
 * Data export (QA A-10).
 *
 * The list was a hard-coded history from July 2025 with invented users, and «Generar archivo»
 * waited 2.5 s on a timer and produced nothing. The datasets are now the ones the API offers this
 * user — only those they may read — and the file is generated by the API, downloaded, and recorded
 * in a history that is real.
 */
@Component({
  selector: 'app-data-exports-page',
  standalone: true,
  imports: [...VX_SORT, 
    ReactiveFormsModule,
    LucideAngularModule,
    TranslateModule,
    ListShellComponent,
    ...VX_FORM_A11Y,
    ...FORMAT_PIPES,
    VxBadgeComponent,
  ],
  templateUrl: './data-exports.page.html',
  styleUrls: ['./data-exports.page.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DataExportsPage implements OnInit {
  private readonly translate = inject(TranslateService);
  /** Sortable by its headers (QA B-01). */
  readonly table = sortable(() => this.history(), { dataset: (run) => this.translate.instant(this.labelOf(run.dataset)), status: (run) => this.translate.instant(this.statusKey(run.status)) });
  private readonly fb = inject(FormBuilder);
  private readonly transfer = inject(DataTransferService);
  private readonly notifications = inject(NotificationService);
  private readonly destroyRef = inject(DestroyRef);

  protected readonly DownloadIcon = DownloadCloud;
  protected readonly SuccessIcon = CheckCircle;
  protected readonly ErrorIcon = AlertCircle;
  protected readonly ProcessingIcon = Loader;
  protected readonly statusTone = transferStatusTone;
  protected readonly statusKey = transferStatusKey;

  readonly datasets = signal<DataTransferDataset[]>([]);
  readonly history = signal<DataTransferRun[]>([]);
  readonly loading = signal(true);
  readonly isGenerating = signal(false);

  readonly exportForm = this.fb.nonNullable.group({
    dataType: ['', [Validators.required]],
    format: ['csv' as DataTransferFormat, [Validators.required]],
  });

  ngOnInit(): void {
    this.transfer
      .datasets()
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe({
        next: (datasets) => this.datasets.set(datasets),
        error: (error: unknown) => this.notifications.showHttpError(error, 'data_exports.datasets_failed'),
      });
    this.loadHistory();
  }

  labelOf(datasetId: string): string {
    return this.datasets().find((dataset) => dataset.id === datasetId)?.labelKey ?? datasetId;
  }

  startExport(): void {
    if (this.exportForm.invalid || this.isGenerating()) return;
    const { dataType, format } = this.exportForm.getRawValue();
    this.isGenerating.set(true);
    this.transfer
      .export(dataType, format)
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe({
        next: (file) => {
          saveFile(file);
          this.isGenerating.set(false);
          this.notifications.showSuccess('data_exports.file_ready', { name: file.fileName });
          this.loadHistory();
        },
        error: (error: unknown) => {
          this.isGenerating.set(false);
          this.notifications.showHttpError(error, 'data_exports.export_failed');
        },
      });
  }

  private loadHistory(): void {
    this.transfer
      .runs('EXPORT')
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe({
        next: (runs) => {
          this.history.set(runs);
          this.loading.set(false);
        },
        error: () => {
          this.history.set([]);
          this.loading.set(false);
        },
      });
  }
}
