import { ModuleManifest, WindowKind } from '../module-manifest';

/**
 * Purchasing: what the company buys, and what it owes for it.
 *
 * Suppliers live here for the same reason customers live in Sales. Requisitions and orders are
 * real documents now: they were declared here while both screens showed rows invented in the
 * browser, so the gap stayed visible in one place instead of being hidden by a menu that silently
 * omitted them.
 */
export const COMPRAS_MODULE: ModuleManifest = {
  id: 'compras',
  titleKey: 'modules.purchasing',
  icon: 'ShoppingCart',
  basePath: '',
  order: 2,
  routes: [
    {
      path: 'accounts-payable',
      kind: WindowKind.LIST,
      permission: 'accounts_payable:view',
      titleKey: 'page_titles.vendor_bills',
      icon: 'FileText',
      entityKeyFn: () => 'compras:bills',
      menu: { group: 'documents', labelKey: 'sidebar.finance.ap_sub.invoices' },
      load: () => import('../../../features/accounts-payable/list/list.page').then((m) => m.VendorBillsListPage),
    },
    {
      path: 'accounts-payable/new',
      kind: WindowKind.DRAFT,
      permission: 'accounts_payable:create',
      titleKey: 'page_titles.vendor_bill_new',
      icon: 'FilePlus',
      entityKeyFn: () => 'compras:bill:new',
      load: () => import('../../../features/accounts-payable/form/form.page').then((m) => m.VendorBillFormPage),
    },
    // Payments to suppliers are documents (audit H-14): a list, the form that makes one, and the
    // payment itself. The menu used to open straight onto the form. All declared before ':id' so
    // the literals never lose the match to the bill's parameter.
    {
      path: 'accounts-payable/payments',
      kind: WindowKind.LIST,
      permission: 'accounts_payable:view',
      titleKey: 'page_titles.vendor_payments',
      icon: 'Banknote',
      entityKeyFn: () => 'compras:payments',
      menu: { group: 'documents', labelKey: 'page_titles.vendor_payments' },
      load: () => import('../../../features/accounts-payable/payments/payments.page').then((m) => m.VendorPaymentsPage),
    },
    {
      path: 'accounts-payable/payments/new',
      kind: WindowKind.DRAFT,
      permission: 'accounts_payable:pay',
      titleKey: 'page_titles.vendor_payment_new',
      icon: 'Banknote',
      entityKeyFn: () => 'compras:payment:new',
      load: () => import('../../../features/accounts-payable/payment/payment.page').then((m) => m.VendorPaymentPage),
    },
    {
      path: 'accounts-payable/payments/:id',
      kind: WindowKind.DOCUMENT,
      permission: 'accounts_payable:view',
      titleKey: 'page_titles.vendor_payment',
      icon: 'Banknote',
      entityKeyFn: (p) => `compras:payment:${p['id']}`,
      load: () => import('../../../features/accounts-payable/payments/payment-detail.page').then((m) => m.VendorPaymentDetailPage),
    },
    // Debit notes to suppliers (audit H-19): the server had them, no screen did.
    {
      path: 'accounts-payable/debit-notes',
      kind: WindowKind.LIST,
      permission: 'accounts_payable:view',
      titleKey: 'page_titles.vendor_debit_notes',
      icon: 'FileMinus',
      entityKeyFn: () => 'compras:debit-notes',
      menu: { group: 'documents', labelKey: 'page_titles.vendor_debit_notes' },
      load: () => import('../../../features/accounts-payable/debit-notes/debit-notes.page').then((m) => m.VendorDebitNotesPage),
    },
    {
      path: 'accounts-payable/debit-notes/new',
      kind: WindowKind.DRAFT,
      permission: 'accounts_payable:create',
      titleKey: 'page_titles.vendor_debit_note_new',
      icon: 'FileMinus',
      entityKeyFn: () => 'compras:debit-note:new',
      load: () => import('../../../features/accounts-payable/debit-notes/debit-note-form.page').then((m) => m.VendorDebitNoteFormPage),
    },
    {
      path: 'accounts-payable/debit-notes/:id',
      kind: WindowKind.DOCUMENT,
      permission: 'accounts_payable:view',
      titleKey: 'page_titles.vendor_debit_note',
      icon: 'FileMinus',
      entityKeyFn: (p) => `compras:debit-note:${p['id']}`,
      load: () => import('../../../features/accounts-payable/debit-notes/debit-note.page').then((m) => m.VendorDebitNotePage),
    },
    {
      path: 'accounts-payable/:id/edit',
      kind: WindowKind.DRAFT,
      permission: 'accounts_payable:edit',
      titleKey: 'page_titles.vendor_bill_edit',
      icon: 'FilePen',
      entityKeyFn: (p) => `compras:bill:${p['id']}:edit`,
      load: () => import('../../../features/accounts-payable/form/form.page').then((m) => m.VendorBillFormPage),
    },
    {
      path: 'accounts-payable/:id',
      kind: WindowKind.DOCUMENT,
      permission: 'accounts_payable:view',
      icon: 'FileText',
      //  Estático hasta que la página sepa el número; ver la nota en `ventas.manifest.ts`.
      titleKey: 'page_titles.vendor_bill',
      entityKeyFn: (p) => `compras:bill:${p['id']}`,
      load: () => import('../../../features/accounts-payable/detail/detail.page').then((m) => m.VendorBillDetailPage),
    },
    {
      path: 'contacts/suppliers',
      kind: WindowKind.LIST,
      permission: 'suppliers:view',
      titleKey: 'page_titles.suppliers',
      icon: 'Truck',
      entityKeyFn: () => 'compras:suppliers',
      menu: { group: 'masters', labelKey: 'sidebar.master_data.suppliers' },
      load: () => import('../../../features/contacts/suppliers/suppliers.page').then((m) => m.SuppliersPage),
    },
    {
      path: 'contacts/suppliers/new',
      kind: WindowKind.DRAFT,
      permission: 'suppliers:create',
      titleKey: 'page_titles.suppliers',
      icon: 'Truck',
      entityKeyFn: () => 'compras:supplier:new',
      load: () => import('../../../features/contacts/supplier-form/supplier-form').then((m) => m.SupplierForm),
    },
    {
      path: 'contacts/suppliers/:id/edit',
      kind: WindowKind.DRAFT,
      permission: 'suppliers:edit',
      titleKey: 'page_titles.supplier_edit',
      icon: 'Truck',
      entityKeyFn: (p) => `compras:supplier:${p['id']}`,
      load: () => import('../../../features/contacts/supplier-form/supplier-form').then((m) => m.SupplierForm),
    },
    {
      path: 'purchasing/orders',
      kind: WindowKind.LIST,
      // `procurement:view`, not `bills:view`: an order is not a bill, and the permission that
      // guarded these screens was one the endpoints behind them do not check.
      permission: 'procurement:view',
      titleKey: 'page_titles.purchase_orders',
      icon: 'ClipboardList',
      entityKeyFn: () => 'compras:orders',
      menu: { group: 'documents', labelKey: 'sidebar.operations.purchasing_sub.orders' },
      load: () => import('../../../features/purchasing/orders/orders.page').then((m) => m.OrdersPage),
    },
    {
      path: 'purchasing/orders/new',
      kind: WindowKind.DRAFT,
      permission: 'procurement:manage',
      titleKey: 'page_titles.purchase_order_new',
      icon: 'ClipboardList',
      entityKeyFn: () => 'compras:order:new',
      load: () => import('../../../features/purchasing/orders/form/form.page').then((m) => m.PurchaseOrderFormPage),
    },
    {
      path: 'purchasing/orders/:id/edit',
      kind: WindowKind.DRAFT,
      permission: 'procurement:view',
      titleKey: 'page_titles.purchase_order_edit',
      icon: 'ClipboardList',
      entityKeyFn: (p) => `compras:order:${p['id']}`,
      load: () => import('../../../features/purchasing/orders/form/form.page').then((m) => m.PurchaseOrderFormPage),
    },
    // Goods receipts are documents (audit H-03): what arrived against an order, listed, opened by
    // themselves, voidable while not billed.
    {
      path: 'purchasing/receipts',
      kind: WindowKind.LIST,
      permission: 'procurement:view',
      titleKey: 'page_titles.goods_receipts',
      icon: 'PackageCheck',
      entityKeyFn: () => 'compras:receipts',
      menu: { group: 'documents', labelKey: 'page_titles.goods_receipts' },
      load: () => import('../../../features/purchasing/receipts/receipts.page').then((m) => m.GoodsReceiptsPage),
    },
    {
      path: 'purchasing/receipts/new',
      kind: WindowKind.DRAFT,
      permission: 'procurement:manage',
      titleKey: 'page_titles.goods_receipt_new',
      icon: 'PackagePlus',
      entityKeyFn: () => 'compras:receipt:new',
      load: () => import('../../../features/purchasing/receipts/receipt-new.page').then((m) => m.GoodsReceiptNewPage),
    },
    {
      path: 'purchasing/receipts/:id',
      kind: WindowKind.DOCUMENT,
      permission: 'procurement:view',
      titleKey: 'page_titles.goods_receipt',
      icon: 'PackageCheck',
      entityKeyFn: (p) => `compras:receipt:${p['id']}`,
      load: () => import('../../../features/purchasing/receipts/receipt.page').then((m) => m.GoodsReceiptPage),
    },
    {
      path: 'purchasing/requisitions',
      kind: WindowKind.LIST,
      permission: 'procurement:view',
      titleKey: 'page_titles.purchase_requisitions',
      icon: 'ClipboardCheck',
      entityKeyFn: () => 'compras:requisitions',
      menu: { group: 'documents', labelKey: 'sidebar.operations.purchasing_sub.requisitions' },
      load: () => import('../../../features/purchasing/requisitions/requisitions.page').then((m) => m.RequisitionsPage),
    },
    {
      path: 'purchasing/requisitions/new',
      kind: WindowKind.DRAFT,
      permission: 'procurement:manage',
      titleKey: 'page_titles.purchase_requisition_new',
      icon: 'ClipboardCheck',
      entityKeyFn: () => 'compras:requisition:new',
      load: () => import('../../../features/purchasing/requisitions/form/form.page').then((m) => m.RequisitionFormPage),
    },
    {
      path: 'purchasing/requisitions/:id/edit',
      kind: WindowKind.DRAFT,
      permission: 'procurement:view',
      titleKey: 'page_titles.purchase_requisition_edit',
      icon: 'ClipboardCheck',
      entityKeyFn: (p) => `compras:requisition:${p['id']}`,
      load: () => import('../../../features/purchasing/requisitions/form/form.page').then((m) => m.RequisitionFormPage),
    },
    {
      path: 'reports/aging/payables',
      kind: WindowKind.OVERVIEW,
      permission: 'accounts_payable:view',
      titleKey: 'page_titles.accounts_payable_aging',
      icon: 'CalendarClock',
      data: { side: 'payables' },
      entityKeyFn: () => 'compras:aging',
      menu: { group: 'analysis', labelKey: 'sidebar.finance.ap_sub.aging' },
      load: () => import('../../../features/reports/aging/aging.page').then((m) => m.AgingPage),
    },
  ],
};
