import { ModuleManifest, WindowKind } from '../module-manifest';

/**
 * Accounting: the ledger and everything that closes it.
 *
 * Twenty-two pages, nineteen of them already wired to working endpoints, and not one of them
 * reached a user: `/accounting/*` was absent from the window catalogue, so every link in this
 * module opened the "under construction" card. Nothing here is new work — it is the same pages,
 * declared where the shell can find them.
 */
export const CONTABILIDAD_MODULE: ModuleManifest = {
  id: 'contabilidad',
  titleKey: 'MODULES.ACCOUNTING',
  icon: 'Landmark',
  basePath: 'accounting',
  order: 6,
  routes: [
    {
      path: 'chart-of-accounts',
      kind: WindowKind.LIST,
      permission: 'coa:view',
      titleKey: 'PAGE_TITLES.CHART_OF_ACCOUNTS',
      icon: 'ListTree',
      entityKeyFn: () => 'contabilidad:coa',
      menu: { group: 'masters', labelKey: 'sidebar.finance.gl_sub.coa' },
      load: () => import('../../../features/accounting/chart-of-accounts/chart-of-accounts.page').then((m) => m.ChartOfAccountsPage),
    },
    {
      path: 'chart-of-accounts/segments-configuration',
      kind: WindowKind.DRAFT,
      permission: 'coa:edit',
      titleKey: 'PAGE_TITLES.SEGMENT_CONFIG',
      icon: 'Blocks',
      entityKeyFn: () => 'contabilidad:coa-segments',
      load: () => import('../../../features/accounting/chart-of-accounts/segment-configuration/segment-configuration.page').then((m) => m.SegmentConfigurationPage),
    },
    {
      path: 'chart-of-accounts/new',
      kind: WindowKind.DRAFT,
      permission: 'coa:create',
      titleKey: 'PAGE_TITLES.ACCOUNT_NEW',
      icon: 'FilePlus',
      entityKeyFn: () => `contabilidad:account:new:${crypto.randomUUID()}`,
      load: () => import('../../../features/accounting/account-form/account-form.page').then((m) => m.AccountFormPage),
    },
    {
      path: 'chart-of-accounts/:id/edit',
      kind: WindowKind.DRAFT,
      permission: 'coa:edit',
      titleKey: 'PAGE_TITLES.ACCOUNT_EDIT',
      icon: 'FilePen',
      entityKeyFn: (p) => `contabilidad:account:${p['id']}`,
      load: () => import('../../../features/accounting/account-form/account-form.page').then((m) => m.AccountFormPage),
    },
    {
      path: 'journal-entries',
      kind: WindowKind.LIST,
      permission: 'journal_entries:view',
      titleKey: 'PAGE_TITLES.JOURNAL_ENTRIES',
      icon: 'BookOpen',
      entityKeyFn: () => 'contabilidad:journal-entries',
      menu: { group: 'documents', labelKey: 'sidebar.finance.gl_sub.journal' },
      load: () => import('../../../features/accounting/journal-entries/journal-entries.page').then((m) => m.JournalEntriesPage),
    },
    {
      path: 'journal-entries/new',
      kind: WindowKind.DRAFT,
      permission: 'journal_entries:create',
      titleKey: 'PAGE_TITLES.JOURNAL_ENTRY_NEW',
      icon: 'FilePlus',
      entityKeyFn: () => `contabilidad:entry:new:${crypto.randomUUID()}`,
      load: () => import('../../../features/accounting/journal-entry-form/journal-entry-form.page').then((m) => m.JournalEntryFormPage),
    },
    {
      //  Un asistente: subir el fichero, mapear las columnas, revisar la previsualización y
      //  confirmar. No hay un borrador que guardar —no existe `FormGroup`, la pantalla es
      //  dirigida por plantilla— y el armazón de borrador impondría un «Guardar» que aquí no
      //  significa nada. Es la misma forma que la importación de datos del área de trabajo.
      path: 'journal-entries/import',
      kind: WindowKind.CANVAS,
      permission: 'journal_entries:create',
      titleKey: 'PAGE_TITLES.JOURNAL_ENTRY_IMPORT',
      icon: 'Upload',
      entityKeyFn: () => 'contabilidad:entry-import',
      load: () => import('../../../features/accounting/journal-entries/import/import.page').then((m) => m.JournalEntryImportPage),
    },
    {
      path: 'journal-entries/:id/edit',
      kind: WindowKind.DRAFT,
      permission: 'journal_entries:edit',
      titleKey: 'PAGE_TITLES.JOURNAL_ENTRY_EDIT',
      icon: 'FilePen',
      entityKeyFn: (p) => `contabilidad:entry:${p['id']}`,
      load: () => import('../../../features/accounting/journal-entry-form/journal-entry-form.page').then((m) => m.JournalEntryFormPage),
    },
    {
      path: 'daily-journal',
      kind: WindowKind.LIST,
      permission: 'journal_entries:view',
      titleKey: 'PAGE_TITLES.DAILY_JOURNAL',
      icon: 'BookText',
      entityKeyFn: () => 'contabilidad:daily-journal',
      menu: { group: 'documents', labelKey: 'sidebar.finance.gl_sub.book_journal' },
      load: () => import('../../../features/accounting/daily-journal/daily-journal.page').then((m) => m.DailyJournalPage),
    },
    {
      path: 'general-ledger',
      kind: WindowKind.LIST,
      permission: 'accounting:view',
      titleKey: 'PAGE_TITLES.GENERAL_LEDGER',
      icon: 'Library',
      entityKeyFn: () => 'contabilidad:general-ledger',
      menu: { group: 'documents', labelKey: 'sidebar.finance.gl_sub.book_gl' },
      load: () => import('../../../features/accounting/general-ledger/general-ledger.page').then((m) => m.GeneralLedgerPage),
    },
    {
      path: 'general-ledger/new',
      kind: WindowKind.DRAFT,
      permission: 'accounting:manage_ledgers',
      titleKey: 'PAGE_TITLES.LEDGER_NEW',
      icon: 'FilePlus',
      entityKeyFn: () => `contabilidad:ledger:new:${crypto.randomUUID()}`,
      load: () => import('../../../features/accounting/ledger-form/app-ledger-form-page').then((m) => m.LedgerFormPage),
    },
    {
      //  Editar un libro reutiliza el mismo formulario (LedgerFormPage acepta `@Input() id`). Sin esta
      //  ruta, «Editar» en la lista de libros caía en la página genérica «en construcción» y, por ser
      //  MODULE_LIST, nunca se abría como vista previa.
      path: 'general-ledger/:id/edit',
      kind: WindowKind.DRAFT,
      permission: 'accounting:manage_ledgers',
      titleKey: 'PAGE_TITLES.LEDGER_EDIT',
      icon: 'Layers3',
      entityKeyFn: (p) => `contabilidad:ledger:${p['id']}`,
      load: () => import('../../../features/accounting/ledger-form/app-ledger-form-page').then((m) => m.LedgerFormPage),
    },
    {
      //  El mayor de una cuenta es el conjunto de sus movimientos: se busca dentro de él, se
      //  acota por fechas y se lee de arriba abajo. Es una lista con una cuenta por encima, no un
      //  documento con estado — la cuenta no se emite ni se anula.
      path: 'general-ledger/:accountId',
      kind: WindowKind.LIST,
      permission: 'accounting:view',
      icon: 'Library',
      titleFn: (p) => `Mayor · ${p['accountId']}`,
      entityKeyFn: (p) => `contabilidad:gl:${p['accountId']}`,
      load: () => import('../../../features/accounting/general-ledger/general-ledger.page').then((m) => m.GeneralLedgerPage),
    },
    {
      path: 'subsidiary-ledgers',
      kind: WindowKind.LIST,
      permission: 'accounting:view',
      titleKey: 'PAGE_TITLES.SUBSIDIARY_LEDGERS',
      icon: 'Layers',
      entityKeyFn: () => 'contabilidad:subsidiary-ledgers',
      menu: { group: 'documents', labelKey: 'sidebar.finance.gl_sub.book_subledgers' },
      load: () => import('../../../features/accounting/subsidiary-ledgers/subsidiary-ledgers.page').then((m) => m.SubsidiaryLedgersPage),
    },
    {
      path: 'ledgers',
      kind: WindowKind.LIST,
      permission: 'accounting:manage_ledgers',
      titleKey: 'PAGE_TITLES.LEDGERS',
      icon: 'Layers3',
      entityKeyFn: () => 'contabilidad:ledgers',
      menu: { group: 'masters', labelKey: 'sidebar.finance.gl_sub.multi_ledger' },
      load: () => import('../../../features/accounting/ledger-list/ledger-list.page').then((m) => m.LedgerListPage),
    },
    {
      path: 'journals',
      kind: WindowKind.LIST,
      permission: 'journal_entries:view',
      titleKey: 'PAGE_TITLES.JOURNALS',
      icon: 'NotebookTabs',
      entityKeyFn: () => 'contabilidad:journals',
      menu: { group: 'masters', labelKey: 'sidebar.finance.gl_sub.journals' },
      load: () => import('../../../features/accounting/journal-list/journal-list.page').then((m) => m.JournalListPage),
    },
    {
      path: 'journals/new',
      kind: WindowKind.DRAFT,
      permission: 'journal_entries:create',
      titleKey: 'PAGE_TITLES.JOURNAL_NEW',
      icon: 'FilePlus',
      entityKeyFn: () => `contabilidad:journal:new:${crypto.randomUUID()}`,
      load: () => import('../../../features/accounting/journal-form/journal-form.page').then((m) => m.JournalFormPage),
    },
    {
      //  Editar un diario usa el mismo formulario (JournalFormPage lee `:id`). Sin esta ruta, «Editar»
      //  en la lista de diarios abría la página genérica «en construcción», no el formulario, y nunca
      //  como vista previa.
      path: 'journals/:id/edit',
      kind: WindowKind.DRAFT,
      permission: 'journal_entries:view',
      titleKey: 'PAGE_TITLES.JOURNAL_EDIT',
      icon: 'NotebookTabs',
      entityKeyFn: (p) => `contabilidad:journal:${p['id']}`,
      load: () => import('../../../features/accounting/journal-form/journal-form.page').then((m) => m.JournalFormPage),
    },
    {
      path: 'periods',
      kind: WindowKind.LIST,
      permission: 'accounting:view',
      titleKey: 'PAGE_TITLES.ACCOUNTING_PERIODS',
      icon: 'CalendarRange',
      entityKeyFn: () => 'contabilidad:periods',
      menu: { group: 'documents', labelKey: 'sidebar.finance.gl_sub.periods' },
      load: () => import('../../../features/accounting/periods/periods.page').then((m) => m.PeriodsPage),
    },
    {
      path: 'variance-analysis',
      kind: WindowKind.OVERVIEW,
      permission: 'budgets:view',
      titleKey: 'PAGE_TITLES.VARIANCE_ANALYSIS',
      icon: 'GitCompareArrows',
      entityKeyFn: () => 'contabilidad:variance',
      menu: { group: 'analysis', labelKey: 'sidebar.finance.gl_sub.variance_analysis' },
      load: () => import('../../../features/accounting/variance-analysis/variance-analysis.page').then((m) => m.VarianceAnalysisPage),
    },
    {
      path: 'closing/month-end',
      kind: WindowKind.OVERVIEW,
      permission: 'accounting:close_period',
      titleKey: 'PAGE_TITLES.CLOSE_MONTH',
      icon: 'CheckCircle',
      entityKeyFn: () => 'contabilidad:month-end',
      menu: { group: 'documents', labelKey: 'sidebar.finance.gl_sub.closing_monthly' },
      load: () => import('../../../features/accounting/closing/month-end-close/month-end-close.page').then((m) => m.MonthEndClosePage),
    },
    {
      path: 'closing/annual-close',
      kind: WindowKind.OVERVIEW,
      permission: 'accounting:close_year',
      titleKey: 'PAGE_TITLES.CLOSE_YEAR',
      icon: 'CalendarCheck',
      entityKeyFn: () => 'contabilidad:annual-close',
      menu: { group: 'documents', labelKey: 'sidebar.finance.gl_sub.closing_annual' },
      load: () => import('../../../features/accounting/closing/annual-close/annual-close.page').then((m) => m.AnnualClosePage),
    },
    {
      path: 'closing/checklist',
      kind: WindowKind.OVERVIEW,
      permission: 'accounting:view',
      titleKey: 'PAGE_TITLES.CLOSING_CHECKLISTS',
      icon: 'ListChecks',
      entityKeyFn: () => 'contabilidad:closing-checklist',
      menu: { group: 'documents', labelKey: 'sidebar.finance.gl_sub.closing_checklist' },
      load: () => import('../../../features/accounting/closing/checklist/checklist.page').then((m) => m.ChecklistPage),
    },
  ],
};
