import { ModuleManifest, WindowKind } from '../module-manifest';

/**
 * Sales: what the company sells, and what it is owed for it.
 *
 * Customers and price lists live here rather than in a "master data" group. That group is being
 * dissolved deliberately: it was defined by shape ("this is a catalogue") instead of by domain, so
 * nobody owned it, and the inventory found 8 of its 13 pages still showing hardcoded rows. A
 * customer belongs to whoever sells to them.
 */
export const VENTAS_MODULE: ModuleManifest = {
  id: 'ventas',
  titleKey: 'MODULES.SALES',
  icon: 'ShoppingBag',
  basePath: '',
  order: 1,
  routes: [
    {
      path: 'invoices',
      kind: WindowKind.LIST,
      permission: 'invoices:view',
      titleKey: 'PAGE_TITLES.INVOICES',
      icon: 'Receipt',
      entityKeyFn: () => 'ventas:invoices',
      menu: { group: 'documents', labelKey: 'sidebar.finance.ar_sub.invoices' },
      load: () => import('../../../features/invoices/list/list.page').then((m) => m.InvoicesListPage),
    },
    {
      path: 'invoices/new',
      kind: WindowKind.DRAFT,
      permission: 'invoices:create',
      titleKey: 'PAGE_TITLES.INVOICE_NEW',
      icon: 'FilePlus',
      // A new invoice is a fresh draft every time: two of them must not collapse into one window.
      entityKeyFn: () => `ventas:invoice:new:${crypto.randomUUID()}`,
      load: () => import('../../../features/invoices/new/new.page').then((m) => m.NewInvoicePage),
    },
    {
      path: 'invoices/:id',
      kind: WindowKind.DOCUMENT,
      permission: 'invoices:view',
      icon: 'FileText',
      titleFn: (p, d) => `Factura ${(d as { number?: string })?.number ?? p['id']}`,
      entityKeyFn: (p) => `ventas:invoice:${p['id']}`,
      load: () => import('../../../features/invoices/detail/detail.page').then((m) => m.InvoiceDetailPage),
    },
    {
      path: 'customer-receipts',
      kind: WindowKind.LIST,
      permission: 'accounts_receivable:view',
      titleKey: 'PAGE_TITLES.CUSTOMER_RECEIPTS',
      icon: 'HandCoins',
      entityKeyFn: () => 'ventas:receipts',
      menu: { group: 'documents', labelKey: 'sidebar.finance.ar_sub.receipts' },
      load: () => import('../../../features/customer-receipts/list/list.page').then((m) => m.CustomerReceiptsListPage),
    },
    {
      path: 'customer-receipts/new',
      kind: WindowKind.DRAFT,
      permission: 'accounts_receivable:collect',
      titleKey: 'PAGE_TITLES.CUSTOMER_RECEIPT_NEW',
      icon: 'HandCoins',
      entityKeyFn: () => `ventas:receipt:new:${crypto.randomUUID()}`,
      load: () => import('../../../features/customer-receipts/form/form.page').then((m) => m.CustomerReceiptFormPage),
    },
    {
      path: 'contacts/customers',
      kind: WindowKind.LIST,
      permission: 'customers:view',
      titleKey: 'PAGE_TITLES.CUSTOMERS',
      icon: 'Users',
      entityKeyFn: () => 'ventas:customers',
      menu: { group: 'masters', labelKey: 'sidebar.master_data.customers' },
      load: () => import('../../../features/contacts/customers/customers.page').then((m) => m.CustomersPage),
    },
    {
      path: 'contacts/customers/new',
      kind: WindowKind.DRAFT,
      permission: 'customers:create',
      titleKey: 'PAGE_TITLES.CUSTOMER_NEW',
      icon: 'UserPlus',
      entityKeyFn: () => `ventas:customer:new:${crypto.randomUUID()}`,
      load: () => import('../../../features/contacts/customer-form/customer-form.page').then((m) => m.CustomerFormPage),
    },
    {
      path: 'contacts/customers/:id/edit',
      kind: WindowKind.DRAFT,
      permission: 'customers:edit',
      titleKey: 'PAGE_TITLES.CUSTOMER_EDIT',
      icon: 'UserCog',
      entityKeyFn: (p) => `ventas:customer:${p['id']}`,
      load: () => import('../../../features/contacts/customer-form/customer-form.page').then((m) => m.CustomerFormPage),
    },
    {
      path: 'masters/price-lists',
      kind: WindowKind.LIST,
      permission: 'price_lists:view',
      titleKey: 'PAGE_TITLES.PRICE_LISTS',
      icon: 'Tag',
      entityKeyFn: () => 'ventas:price-lists',
      menu: { group: 'masters', labelKey: 'sidebar.master_data.price_lists' },
      load: () => import('../../../features/masters/price-lists/price-lists.page').then((m) => m.PriceListsPage),
    },
    {
      path: 'masters/price-lists/new',
      kind: WindowKind.DRAFT,
      permission: 'price_lists:create',
      titleKey: 'PAGE_TITLES.PRICE_LIST_NEW',
      icon: 'Tag',
      entityKeyFn: () => `ventas:price-list:new:${crypto.randomUUID()}`,
      load: () => import('../../../features/masters/price-lists/price-lists-form/price-list-form.page').then((m) => m.PriceListFormPage),
    },
    {
      path: 'masters/price-lists/:id/edit',
      kind: WindowKind.DRAFT,
      permission: 'price_lists:edit',
      titleKey: 'PAGE_TITLES.PRICE_LIST_EDIT',
      icon: 'Tag',
      entityKeyFn: (p) => `ventas:price-list:${p['id']}`,
      load: () => import('../../../features/masters/price-lists/price-lists-form/price-list-form.page').then((m) => m.PriceListFormPage),
    },
    {
      path: 'sales/history',
      kind: WindowKind.LIST,
      permission: 'invoices:view',
      titleKey: 'PAGE_TITLES.SALES_HISTORY',
      icon: 'History',
      entityKeyFn: () => 'ventas:history',
      load: () => import('../../../features/sales/history/history.page').then((m) => m.HistoryPage),
    },
    {
      path: 'sales/pos',
      kind: WindowKind.DRAFT,
      permission: 'invoices:create',
      titleKey: 'PAGE_TITLES.POINT_OF_SALE',
      icon: 'Store',
      entityKeyFn: () => 'ventas:pos',
      load: () => import('../../../features/sales/pos/pos.page').then((m) => m.PosPage),
    },
    {
      path: 'reports/aging/receivables',
      kind: WindowKind.OVERVIEW,
      permission: 'accounts_receivable:view',
      titleKey: 'PAGE_TITLES.ACCOUNTS_RECEIVABLE_AGING',
      icon: 'CalendarClock',
      data: { side: 'receivables' },
      entityKeyFn: () => 'ventas:aging',
      menu: { group: 'analysis', labelKey: 'sidebar.finance.ar_sub.aging' },
      load: () => import('../../../features/reports/aging/aging.page').then((m) => m.AgingPage),
    },
  ],
};
