import { ModuleManifest, WindowKind } from '../module-manifest';

/**
 * The workspace itself: what belongs to no single domain.
 *
 * Home, the user's queue, approvals, notifications, search and the import/export ledger. They are
 * grouped here rather than scattered because none of them is owned by Sales or Accounting — they
 * are the shell the modules live in.
 */
export const WORKSPACE_MODULE: ModuleManifest = {
  id: 'workspace',
  titleKey: 'MODULES.WORKSPACE',
  icon: 'LayoutGrid',
  basePath: '',
  order: 0,
  routes: [
    {
      path: 'overview',
      kind: WindowKind.OVERVIEW,
      permission: 'authenticated',
      titleKey: 'PAGE_TITLES.HOME',
      icon: 'Home',
      isCloseable: false,
      entityKeyFn: () => 'workspace:overview',
      menu: { group: 'inbox', labelKey: 'sidebar.general.overview' },
      load: () => import('../../../features/overview/overview.page').then((m) => m.OverviewPage),
    },
    {
      path: 'my-work',
      kind: WindowKind.INBOX,
      permission: 'authenticated',
      titleKey: 'PAGE_TITLES.MY_WORK',
      icon: 'ClipboardList',
      entityKeyFn: () => 'workspace:my-work',
      menu: { group: 'inbox', labelKey: 'sidebar.general.my_work' },
      load: () => import('../../../features/my-work/my-work.page').then((m) => m.MyWorkPage),
    },
    {
      path: 'approvals',
      kind: WindowKind.INBOX,
      permission: 'workflows:decide',
      titleKey: 'PAGE_TITLES.APPROVALS',
      icon: 'CheckSquare',
      entityKeyFn: () => 'workspace:approvals',
      menu: { group: 'inbox', labelKey: 'sidebar.general.approvals' },
      load: () => import('../../../features/approvals/approvals.page').then((m) => m.ApprovalsPage),
    },
    {
      path: 'dashboard',
      kind: WindowKind.OVERVIEW,
      permission: 'dashboard:view',
      titleKey: 'PAGE_TITLES.DASHBOARD',
      icon: 'LayoutDashboard',
      entityKeyFn: () => 'workspace:dashboard',
      menu: { group: 'analysis', labelKey: 'sidebar.general.dashboard' },
      load: () => import('../../../features/dashboard/dashboard.page').then((m) => m.DashboardPage),
    },
    {
      path: 'notifications',
      kind: WindowKind.LIST,
      permission: 'authenticated',
      titleKey: 'PAGE_TITLES.NOTIFICATIONS',
      icon: 'Bell',
      entityKeyFn: () => 'workspace:notifications',
      menu: { group: 'inbox', labelKey: 'sidebar.general.notifications' },
      load: () => import('../../../features/notifications/notifications.page').then((m) => m.NotificationsPage),
    },
    {
      path: 'global-search',
      kind: WindowKind.LIST,
      permission: 'authenticated',
      titleKey: 'PAGE_TITLES.SEARCH',
      icon: 'Search',
      entityKeyFn: () => 'workspace:global-search',
      load: () => import('../../../features/global-search/global-search.page').then((m) => m.GlobalSearchPage),
    },
    {
      path: 'data-imports',
      kind: WindowKind.LIST,
      permission: 'settings:edit_company',
      titleKey: 'PAGE_TITLES.DATA_IMPORTS',
      icon: 'UploadCloud',
      entityKeyFn: () => 'workspace:data-imports',
      load: () => import('../../../features/data-imports/data-imports.page').then((m) => m.DataImportsPage),
    },
    {
      path: 'data-exports',
      kind: WindowKind.LIST,
      permission: 'settings:edit_company',
      titleKey: 'PAGE_TITLES.DATA_EXPORTS',
      icon: 'DownloadCloud',
      entityKeyFn: () => 'workspace:data-exports',
      load: () => import('../../../features/data-exports/data-exports.page').then((m) => m.DataExportsPage),
    },
    {
      path: 'documents/repository',
      kind: WindowKind.LIST,
      permission: 'authenticated',
      titleKey: 'PAGE_TITLES.DOCUMENT_REPOSITORY',
      icon: 'FolderArchive',
      entityKeyFn: () => 'workspace:documents',
      menu: { group: 'documents', labelKey: 'sidebar.general.documents_sub.all' },
      load: () => import('../../../features/documents/repository/repository.page').then((m) => m.RepositoryPage),
    },
    {
      path: 'documents/templates',
      kind: WindowKind.LIST,
      permission: 'authenticated',
      titleKey: 'PAGE_TITLES.DOCUMENT_TEMPLATES',
      icon: 'FileText',
      entityKeyFn: () => 'workspace:document-templates',
      menu: { group: 'documents', labelKey: 'sidebar.general.documents_sub.templates' },
      load: () => import('../../../features/documents/templates/templates.page').then((m) => m.TemplatesPage),
    },
    {
      path: 'unauthorized',
      kind: WindowKind.OVERVIEW,
      permission: 'authenticated',
      titleKey: 'PAGE_TITLES.ACCESS_DENIED',
      icon: 'ShieldAlert',
      entityKeyFn: () => 'workspace:unauthorized',
      load: () => import('../../../features/unauthorized/unauthorized.page').then((m) => m.UnauthorizedPage),
    },
  ],
};
